import { universalContactCta } from "./contact-cta.mjs";
import { getArticles } from "../server/data-store.mjs";

export const blogArticles = getArticles();

const escapeHtml = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const arrow = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 7h10v10"></path><path d="M7 17 17 7"></path></svg>';
const blogDocumentStyles = '<link rel="icon" href="/favicon.svg"/><link rel="stylesheet" href="/_next/static/css/index.C91Two5O.css"/><link rel="stylesheet" href="/team-brand.css"/><link rel="stylesheet" href="/blog.css?v=article-layout-4"/><link rel="stylesheet" href="/universal-contact.css?v=1"/><link rel="stylesheet" href="/liquid-glass.css"/>';
const blogHeader = `<div class="site-header-shell"><header class="site-header"><a class="brand" href="/" aria-label="Fizyoterapistler Sılasu Turhan ve Tilbe Meriç ana sayfa"><span class="brand-mark"><span></span></span><span>Fizyoterapist<small>Sılasu Turhan · Tilbe Meriç</small></span></a><nav class="desktop-nav" aria-label="Ana menü"><a href="/#hizmetler">Hizmetler</a><a href="/#yaklasim">Yaklaşımımız</a><a href="/uzmanlar">Uzmanlarımız</a><a href="/multisport">MultiSport</a><a href="/blog/" aria-current="page">Makaleler</a><a href="/#iletisim">İletişim</a></nav><div class="header-actions"><div class="language-switcher"><button class="language-trigger" type="button" aria-label="Dil seçin"><img src="https://flagcdn.com/tr.svg" alt=""/><span>TR</span></button></div><button class="header-cta" type="button" data-blog-appointment><span>Randevu</span>${arrow}</button><button class="menu-toggle" type="button" aria-label="Menüyü aç" aria-expanded="false" data-blog-menu-toggle><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M4 5h16"></path><path d="M4 12h16"></path><path d="M4 19h16"></path></svg></button></div><nav class="mobile-menu" aria-label="Mobil menü" data-blog-menu><a href="/#hizmetler">Hizmetler${arrow}</a><a href="/#yaklasim">Yaklaşımımız${arrow}</a><a href="/uzmanlar">Uzmanlarımız${arrow}</a><a href="/multisport">MultiSport${arrow}</a><a href="/blog/" aria-current="page">Makaleler${arrow}</a><a href="/#iletisim">İletişim${arrow}</a><button class="mobile-menu-cta" type="button" data-blog-appointment>Randevu oluştur ${arrow}</button></nav></header></div>`;
const blogFooter = `<footer><a class="brand footer-brand" href="/"><span class="brand-mark"><span></span></span><span>Fizyoterapist<small>Sılasu Turhan · Tilbe Meriç</small></span></a><p>© 2026 Fizyoterapist Sılasu Turhan · Tilbe Meriç</p><p>Randevu ile hizmet verilmektedir.</p></footer><script defer src="/blog-shell.js"></script><script defer src="/navigation-unifier.js?v=fast-3"></script><script defer src="/header-runtime.js?v=header-2"></script>`;

export const blogSectionMarkup = `<section class="blog-section" id="makaleler" aria-labelledby="blog-title"><div class="blog-heading"><p class="eyebrow"><span></span> FİZYOTERAPİ REHBERİ</p><div><h2 id="blog-title">Hareket hakkında<br/><em>okunacaklar.</em></h2><p>Maltepe ve İstanbul'da fizyoterapi, rehabilitasyon ve günlük hareket hakkında anlaşılır içerikler.</p></div><div class="blog-controls"><button type="button" data-blog-direction="previous" aria-label="Önceki makaleler">←</button><button type="button" data-blog-direction="next" aria-label="Sonraki makaleler">→</button></div></div><div class="blog-track" data-blog-track>${blogArticles.map((article, index) => `<article class="blog-card"><img class="blog-card-image" src="${article.cover}" alt="${escapeHtml(article.coverAlt)}" loading="lazy" width="1280" height="720"/><div class="blog-card-content"><p>${escapeHtml(article.topic)} · ${article.readingTime}</p><h3>${escapeHtml(article.title)}</h3><p>${escapeHtml(article.excerpt)}</p><a href="/blog/${article.slug}/">Makaleyi okuyun <span aria-hidden="true">↗</span></a></div></article>`).join("")}</div><a class="blog-all-link" href="/blog/">Tüm makaleleri inceleyin <span aria-hidden="true">↗</span></a></section>`;

export function renderBlogIndex() {
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="description" content="Maltepe ve İstanbul'da fizyoterapi, kinezyoterapi ve rehabilitasyon hakkında rehber makaleler."/><meta name="robots" content="index,follow"/><link rel="canonical" href="https://www.turhanmeric.com/blog/"/><title>Fizyoterapi Rehberi | Maltepe ve İstanbul</title>${blogDocumentStyles}</head><body class="blog-page">${blogHeader}<main><section class="blog-index-hero"><p>FİZYOTERAPİ REHBERİ</p><h1>Hareket hakkında<br/><em>bilinmesi gerekenler.</em></h1><p>Maltepe ve İstanbul'da fizyoterapi, rehabilitasyon ve hareket planı hakkında güncel, anlaşılır makaleler.</p></section><section class="blog-index-grid">${blogArticles.map((article) => `<article><img class="blog-index-cover" src="${article.cover}" alt="${escapeHtml(article.coverAlt)}" loading="lazy" width="1280" height="720"/><p>${escapeHtml(article.topic)} · ${article.readingTime}</p><h2>${escapeHtml(article.title)}</h2><p>${escapeHtml(article.excerpt)}</p><a href="/blog/${article.slug}/"><span>Makaleyi okuyun</span>${arrow}</a></article>`).join("")}</section>${universalContactCta}</main>${blogFooter}</body></html>`;
}

export function renderArticlePage(article) {
  const url = `https://www.turhanmeric.com/blog/${article.slug}/`;
  const relatedArticles = blogArticles.filter((item) => item.slug !== article.slug).slice(0, 3);
  const articleSchema = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    description: article.excerpt,
    mainEntityOfPage: url,
    image: [`https://www.turhanmeric.com${article.cover}`],
    author: { "@type": "Organization", name: "Fizyoterapistler Sılasu Turhan ve Tilbe Meriç" },
    publisher: { "@type": "Organization", name: "Fizyoterapistler Sılasu Turhan ve Tilbe Meriç", url: "https://www.turhanmeric.com/" },
    inLanguage: "tr-TR"
  });
  const breadcrumbSchema = JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana sayfa", item: "https://www.turhanmeric.com/" }, { "@type": "ListItem", position: 2, name: "Makaleler", item: "https://www.turhanmeric.com/blog/" }, { "@type": "ListItem", position: 3, name: article.title, item: url }] });
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="description" content="${escapeHtml(article.excerpt)}"/><meta name="robots" content="index,follow"/><link rel="canonical" href="${url}"/><meta property="og:type" content="article"/><meta property="og:title" content="${escapeHtml(article.title)}"/><meta property="og:description" content="${escapeHtml(article.excerpt)}"/><meta property="og:image" content="https://www.turhanmeric.com${article.cover}"/><meta property="og:image:alt" content="${escapeHtml(article.coverAlt)}"/><title>${escapeHtml(article.title)} | Fizyoterapi Rehberi</title>${blogDocumentStyles}<script type="application/ld+json">${articleSchema}</script><script type="application/ld+json">${breadcrumbSchema}</script></head><body class="blog-page">${blogHeader}<main><article class="blog-article"><nav class="article-breadcrumb" aria-label="Breadcrumb"><a href="/">Ana sayfa</a><span aria-hidden="true"></span><a href="/blog/">Makaleler</a></nav><div class="article-meta"><span>${escapeHtml(article.topic)}</span><i aria-hidden="true"></i><span>${article.readingTime}</span></div><h1>${escapeHtml(article.title)}</h1><figure class="blog-cover"><img src="${article.cover}" alt="${escapeHtml(article.coverAlt)}" width="1280" height="720" fetchpriority="high"/><figcaption><span>Fizyoterapi rehberi</span><span>${article.readingTime}</span></figcaption></figure><p class="blog-answer">${escapeHtml(article.answer)}</p>${article.sections.map(([heading, text]) => `<section><h2>${escapeHtml(heading)}</h2><p>${escapeHtml(text)}</p></section>`).join("")}<aside><strong>Bilgilendirme</strong><p>Bu makale genel bilgi içindir; tanı ve kişisel tedavi önerisi yerine geçmez. Size uygun yaklaşım için değerlendirme gerekir.</p></aside><a class="blog-appointment" href="/?randevu=1">Randevu planlayın ${arrow}</a></article><section class="blog-related" aria-labelledby="related-title"><div><p class="blog-kicker">OKUMAYA DEVAM EDİN</p><h2 id="related-title">Benzer <em>rehberler.</em></h2></div><div class="blog-related-grid">${relatedArticles.map((item) => `<a href="/blog/${item.slug}/"><img src="${item.cover}" alt="${escapeHtml(item.coverAlt)}" loading="lazy" width="1280" height="720"/><span>${escapeHtml(item.topic)}</span><strong>${escapeHtml(item.title)}</strong><small>Makale →</small></a>`).join("")}</div></section>${universalContactCta}</main>${blogFooter}</body></html>`;
}

export default function handler(request, response) {
  const baseUrl = "https://www.turhanmeric.com";
  const url = new URL(request.url, baseUrl);
  const article = blogArticles.find((item) => item.slug === url.searchParams.get("slug"));
  const markup = url.searchParams.has("slug") && !article
    ? "<!doctype html><html lang=\"tr\"><title>Makale bulunamadı</title><body>Makale bulunamadı.</body></html>"
    : article
      ? renderArticlePage(article)
      : renderBlogIndex();

  response.statusCode = article || !url.searchParams.has("slug") ? 200 : 404;
  response.setHeader("content-type", "text/html; charset=utf-8");
  response.end(markup);
}
